# Generated by Django 5.1.4 on 2024-12-28 23:44

import django.db.models.deletion
import shortuuid.django_fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('account_balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=15, verbose_name='balance')),
                ('account_number', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=12, prefix='231', unique=True)),
                ('account_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=15, prefix='UAM', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('account_status', models.CharField(choices=[('in-activa', 'inactive'), ('active', 'active')], default='in-active', max_length=50, verbose_name='status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-date'],
            },
        ),
    ]
