# Generated by Django 5.1.4 on 2024-12-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('in-activa', 'inactive'), ('active', 'active')], default='active', max_length=50, verbose_name='status'),
        ),
    ]
