# Generated by Django 5.1.4 on 2025-01-17 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_account_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='account_owner'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_code', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('initiated_by', models.CharField(default='User', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('Electricity', 'Electricity'), ('Transfer-In', 'Transfer-In'), ('Transfer-Out', 'Transfer-Out'), ('Deposite', 'Deposite'), ('Withdraw', 'Withdraw'), ('Others', 'Others')], max_length=50)),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('network_provider', models.CharField(blank=True, max_length=50)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('api_provider', models.CharField(blank=True, max_length=100)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('transfer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Transfer_in', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
