# Generated by Django 5.1.4 on 2025-01-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_user_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transfer',
            new_name='receiver',
        ),
    ]
