# Generated by Django 5.1.4 on 2025-02-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_transaction_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.AddField(
            model_name='account',
            name='account_bank_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Account Bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_numbers',
            field=models.ManyToManyField(blank=True, to='account.account', verbose_name=''),
        ),
    ]
