# Generated by Django 5.1.4 on 2025-02-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_account_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_bank_name',
            new_name='bank_name',
        ),
    ]
