# Generated by Django 5.1.4 on 2025-02-27 21:12

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_account_bank_name_account_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_numbers',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=15, prefix='UAM', primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Account Bank')),
                ('date_created', models.DateTimeField(verbose_name='date_joined')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_numbers', to='account.account', verbose_name='')),
            ],
            options={
                'verbose_name': 'Account Number',
                'verbose_name_plural': 'Account Numbers',
                'ordering': ['-date_created'],
            },
        ),
    ]
