# Generated by Django 5.1.4 on 2025-02-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_account_account_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountnumber',
            name='flw_ref',
            field=models.CharField(default=1, max_length=50, verbose_name='creation ref'),
            preserve_default=False,
        ),
    ]
