# Generated by Django 5.1.4 on 2025-02-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_accountnumber_flw_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnumber',
            name='account_number',
            field=models.CharField(editable=False, max_length=50, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='accountnumber',
            name='bank_name',
            field=models.CharField(editable=False, max_length=50, verbose_name='Account Bank'),
        ),
        migrations.AlterField(
            model_name='accountnumber',
            name='flw_ref',
            field=models.CharField(editable=False, max_length=50, verbose_name='creation ref'),
        ),
    ]
