# Generated by Django 5.1.4 on 2025-02-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_accountnumber_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnumber',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountnumbers', to='account.account', verbose_name=''),
        ),
    ]
