# Generated by Django 5.1.4 on 2025-02-28 23:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_accountnumber_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('trx_id', models.CharField(blank=True, max_length=200, verbose_name='Api Trx Id')),
                ('trx_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('originator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('originator_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('originator_acc_num', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('transaction_type', models.CharField(choices=[('Transfer-In', 'Transfer-In'), ('Transfer-Out', 'Transfer-Out'), ('Deposite', 'Deposite'), ('Withdraw', 'Withdraw'), ('Refund', 'Refund')], max_length=50)),
                ('payment_type', models.CharField(blank=True, max_length=50)),
                ('trx_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Transfer_in', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
