# Generated by Django 5.1.4 on 2025-03-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_moneytransaction_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransaction',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='transaction_type',
            field=models.CharField(max_length=50),
        ),
    ]
