# Generated by Django 5.1.4 on 2025-04-15 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_moneytransaction_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(editable=False, max_length=50, verbose_name='Account Number')),
                ('account_name', models.CharField(editable=False, max_length=50, verbose_name='Account Name')),
                ('bank_name', models.CharField(editable=False, max_length=50, verbose_name='Account Bank')),
                ('bank_code', models.CharField(editable=False, max_length=50, verbose_name='Account code')),
                ('date_created', models.DateTimeField(verbose_name='date_joined')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawalaccounts', to='account.account', verbose_name='')),
            ],
            options={
                'verbose_name': 'Withdrawal Account ',
                'verbose_name_plural': 'Withdrawal Account ',
                'ordering': ['-date_created'],
            },
        ),
    ]
