# Generated by Django 5.1.4 on 2025-04-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_withdrawalaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalaccount',
            options={'ordering': ['-date_created'], 'verbose_name': 'Withdrawal Account ', 'verbose_name_plural': 'Withdrawal Accounts '},
        ),
        migrations.AlterField(
            model_name='withdrawalaccount',
            name='bank_code',
            field=models.CharField(editable=False, max_length=50, verbose_name='Account Code'),
        ),
        migrations.AlterField(
            model_name='withdrawalaccount',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_joined'),
        ),
    ]
