# Generated by Django 5.1.4 on 2025-04-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_withdrawalaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneytransaction',
            options={'ordering': ['-trx_date'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
