# Generated by Django 5.1.4 on 2025-04-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_moneytransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransaction',
            name='withdrawal_account_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='moneytransaction',
            name='withdrawal_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='moneytransaction',
            name='withdrawal_bank_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='moneytransaction',
            name='withdrawal_bank_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
