# Generated by Django 5.1.4 on 2025-06-14 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_moneytransaction_read_by_approver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalaccount',
            name='is_default',
            field=models.BooleanField(default=True, verbose_name='is default'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approvedtrx', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfersin', to=settings.AUTH_USER_MODEL),
        ),
    ]
