# Generated by Django 5.1.4 on 2025-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneynotification',
            options={'verbose_name': 'Money Notification', 'verbose_name_plural': 'Money Notifications'},
        ),
        migrations.AddField(
            model_name='moneynotification',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='viewed'),
        ),
    ]
