# Generated by Django 5.1.4 on 2025-03-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_delete_moneynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default=1, max_length=50, verbose_name='Notif Type'),
            preserve_default=False,
        ),
    ]
