# Generated by Django 5.1.4 on 2025-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('success', 'success'), ('promotion', 'promotion'), ('info', 'info')], default='success', max_length=50, verbose_name=' Type'),
        ),
    ]
